import type { Branch, Commit } from "./types";

/**
 * The career as a git history.
 *
 * `main` is the career itself. Every employer, the freelance practice, open
 * source and education are branches that fork from `main` when they start and
 * merge back when they end (open branches are current). A commit with extra
 * `parents` on another branch is a collaboration or hand-off.
 *
 * Dates marked `approx: true` are best estimates within a role and are shown
 * with a "≈". Replace them with real months when known.
 */
export const branches: Branch[] = [
  { id: "main", label: "main", kind: "main", color: "#22c55e" },
  {
    id: "novabyte",
    label: "novabyte",
    kind: "employer",
    color: "#38bdf8",
    summary: "NovaByte Solutions Inc. — software consultancy building healthcare, real-estate and fintech platforms for North American clients.",
    location: "Nova Scotia, Canada · remote",
  },
  {
    id: "sabana",
    label: "sabana",
    kind: "employer",
    color: "#f59e0b",
    summary: "Sabana — ride-hailing and logistics platform: driver app, customer product, partner admin panel and backend services.",
    location: "Tehran, Iran · hybrid",
  },
  {
    id: "hoomaan",
    label: "hoomaan",
    kind: "employer",
    color: "#a78bfa",
    summary: "Hoomaan — mobile agency shipping e-commerce and taxi-hailing apps for clients.",
    location: "Mashhad, Iran",
  },
  {
    id: "dayamooz",
    label: "dayamooz",
    kind: "employer",
    color: "#fb7185",
    summary: "Dayamooz — education product; Android app migrated from native Java to React Native.",
    location: "Mashhad, Iran",
  },
  {
    id: "freelance",
    label: "freelance",
    kind: "freelance",
    color: "#2dd4bf",
    summary: "Independent contracts for clients in Dubai, Armenia and the US — nine web and mobile products delivered solo from requirements to release.",
  },
  {
    id: "oss",
    label: "open-source",
    kind: "oss",
    color: "#e879f9",
    summary: "Published React Native components on npm and public tooling on GitHub.",
  },
  {
    id: "education",
    label: "education",
    kind: "education",
    color: "#94a3b8",
    summary: "Azad University (IAU), Tehran — Electrical & Electronics Engineering.",
  },
];

export const commits: Commit[] = [
  // ───────────── education ─────────────
  {
    id: "edu-start",
    branch: "education",
    date: "2012-09",
    kind: "branch",
    parents: ["main-init"],
    title: "Enrolled: Electrical & Electronics Engineering, Azad University (IAU), Tehran",
  },
  {
    id: "edu-msc",
    branch: "education",
    date: "2018-06",
    kind: "merge",
    approx: true,
    title: "MSc awarded — thesis on secure transfer of vital patient data via Android and iOS apps",
    body: "The thesis is where healthcare data and mobile engineering first met — the same problem space as today's EHR work.",
    tags: ["MSc"],
  },

  // ───────────── main ─────────────
  {
    id: "main-init",
    branch: "main",
    date: "2012-09",
    title: "init: engineering studies begin",
  },
  {
    id: "main-first-role",
    branch: "main",
    date: "2016-02",
    title: "First full-time engineering role",
    body: "Android developer at Dayamooz while completing the degree.",
  },

  // ───────────── freelance (2015 → present) ─────────────
  {
    id: "fl-start",
    branch: "freelance",
    date: "2015-01",
    kind: "branch",
    parents: ["main-init"],
    title: "Started freelance practice",
    body: "Part-time contracts run alongside every full-time role since — each engagement handled solo from requirements to delivery.",
  },
  {
    id: "fl-taxi-pair",
    branch: "freelance",
    date: "2018-07",
    approx: true,
    title: "Customer + driver taxi-hailing app pair for a Dubai client",
    body: "Two React Native apps sharing one backend — the same domain later owned at scale at Sabana.",
    stack: ["React Native", "Node.js"],
    parents: ["hm-taxi"],
    people: ["Dubai client"],
  },
  {
    id: "fl-hometrust",
    branch: "freelance",
    date: "2020-06",
    approx: true,
    title: "HomeTrust — admin panel and web app",
    stack: ["React", "Node.js", "MongoDB"],
    people: ["US client"],
  },
  {
    id: "fl-travellead",
    branch: "freelance",
    date: "2021-09",
    approx: true,
    title: "TravelLeadApp — lead-management app",
    stack: ["React Native", "Firebase"],
  },
  {
    id: "fl-dayra-sadaf",
    branch: "freelance",
    date: "2023-03",
    approx: true,
    title: "Dayra and Sadaf — marketing site, web app and API for each",
    body: "Two products for an Armenian client, each shipped as a marketing site, a web app and a REST API.",
    stack: ["Next.js", "NestJS", "PostgreSQL"],
    people: ["Armenian client"],
  },

  // ───────────── dayamooz (2016-02 → 2017-10) ─────────────
  {
    id: "dm-start",
    branch: "dayamooz",
    date: "2016-02",
    kind: "branch",
    parents: ["main-first-role"],
    title: "Joined Dayamooz as Android Developer",
    stack: ["Java", "Android"],
  },
  {
    id: "dm-migration",
    branch: "dayamooz",
    date: "2017-03",
    approx: true,
    title: "Migrated the core Android app from native Java to React Native",
    body: "One codebase instead of two, shorter release cycles and a faster app — the migration that set the direction for the next decade.",
    stack: ["React Native", "Java"],
  },
  {
    id: "dm-redesign",
    branch: "dayamooz",
    date: "2017-08",
    approx: true,
    kind: "merge",
    title: "Launched the redesigned interface with the UI/UX team",
    people: ["UI/UX team"],
    tags: ["redesign live"],
  },
  {
    id: "dm-end",
    branch: "main",
    date: "2017-10",
    kind: "merge",
    parents: ["dm-redesign"],
    title: "Dayamooz → merged into main (Oct 2017)",
  },

  // ───────────── hoomaan (2017-10 → 2018-06) ─────────────
  {
    id: "hm-start",
    branch: "hoomaan",
    date: "2017-10",
    kind: "branch",
    parents: ["dm-end"],
    title: "Joined Hoomaan as React Native Developer",
  },
  {
    id: "hm-ecommerce",
    branch: "hoomaan",
    date: "2018-01",
    approx: true,
    title: "Shipped an e-commerce app to iOS and Android from scratch",
    stack: ["React Native", "REST"],
    tags: ["App Store", "Google Play"],
  },
  {
    id: "hm-taxi",
    branch: "hoomaan",
    date: "2018-04",
    approx: true,
    title: "Shipped a taxi-hailing app to both stores, leading React Native end-to-end",
    body: "Owned front-end delivery and third-party API integration and hit the client launch dates.",
    stack: ["React Native", "Maps", "Payments"],
    tags: ["App Store", "Google Play"],
  },
  {
    id: "hm-end",
    branch: "main",
    date: "2018-06",
    kind: "merge",
    parents: ["hm-taxi"],
    title: "Hoomaan → merged into main (Jun 2018)",
  },

  // ───────────── sabana (2018-04 → 2025-03) ─────────────
  {
    id: "sb-start",
    branch: "sabana",
    date: "2018-04",
    kind: "branch",
    parents: ["hm-taxi"],
    title: "Joined Sabana — front-end features on the driver app",
    stack: ["React Native", "Redux"],
  },
  {
    id: "sb-customer",
    branch: "sabana",
    date: "2019-06",
    approx: true,
    title: "Built the customer product on React and Next.js",
    stack: ["React", "Next.js"],
  },
  {
    id: "sb-admin",
    branch: "sabana",
    date: "2020-05",
    approx: true,
    title: "Delivered the partner admin panel; took ownership of the whole front-end estate",
    stack: ["React", "TypeScript"],
  },
  {
    id: "sb-perf",
    branch: "sabana",
    date: "2021-03",
    approx: true,
    title: "perf: 70% improvement in app performance",
    body: "Profiling, render optimisation and list virtualisation across the driver and customer apps.",
    stack: ["React Native", "Profiling"],
    tags: ["-70% overhead"],
  },
  {
    id: "sb-ui-lib",
    branch: "sabana",
    date: "2022-02",
    approx: true,
    title: "Shared UI component library for web/mobile parity",
    body: "Unit-tested components used by both the React web apps and the React Native apps, with cross-platform debugging as part of every release.",
    stack: ["React", "React Native", "Jest"],
  },
  {
    id: "sb-mentoring",
    branch: "sabana",
    date: "2022-09",
    approx: true,
    kind: "merge",
    title: "Mentees' React Native modules merged after review",
    body: "Code review and hands-on guidance on React and React Native patterns for junior developers, alongside delivery work.",
    people: ["Junior developers"],
  },
  {
    id: "sb-sms",
    branch: "sabana",
    date: "2023-04",
    approx: true,
    title: "NestJS microservice: SMS notification service",
    stack: ["NestJS", "Node.js", "GitHub Actions"],
    tags: ["deployed via CI/CD"],
  },
  {
    id: "sb-ics2",
    branch: "sabana",
    date: "2024-02",
    approx: true,
    title: "NestJS microservice: EU customs (ICS2/ENS) data-exchange integration",
    body: "Compliance-critical integration with the EU Import Control System, deployed through GitHub Actions.",
    stack: ["NestJS", "REST", "GitHub Actions"],
  },
  {
    id: "sb-end",
    branch: "main",
    date: "2025-03",
    kind: "merge",
    parents: ["sb-ics2"],
    title: "Sabana → merged into main after seven years (Mar 2025)",
  },

  // ───────────── open source ─────────────
  {
    id: "oss-start",
    branch: "oss",
    date: "2022-05",
    kind: "branch",
    parents: ["sb-ui-lib"],
    title: "Published react-native-gp-button and react-native-dropdown-searchable on npm",
    body: "Components extracted from day-to-day work: a button group and a searchable FlatList dropdown.",
    tags: ["npm 1.0.3", "npm 1.0.1"],
    links: [
      { label: "react-native-gp-button", href: "https://www.npmjs.com/package/react-native-gp-button" },
      { label: "react-native-dropdown-searchable", href: "https://www.npmjs.com/package/react-native-dropdown-searchable" },
    ],
    stack: ["React Native", "npm"],
  },
  {
    id: "oss-vpn-tester",
    branch: "oss",
    date: "2026-04",
    title: "windscribe-vpn-tester — automated latency/reliability tester for every VPN location and protocol",
    links: [{ label: "GitHub", href: "https://github.com/KianooshSoleimani/windscribe-vpn-tester" }],
    stack: ["Node.js", "macOS", "Windows"],
  },

  // ───────────── novabyte (2025-03 → present) ─────────────
  {
    id: "nb-start",
    branch: "novabyte",
    date: "2025-03",
    kind: "branch",
    parents: ["sb-end"],
    title: "Joined NovaByte Solutions as Full-Stack Developer",
  },
  {
    id: "nb-clients",
    branch: "novabyte",
    date: "2025-05",
    approx: true,
    title: "Full-stack features for EVNS (real estate) and Arcarius Capital (fintech)",
    body: "React, Next.js and React Native front ends against Node.js, NestJS and GraphQL back ends, delivered in Agile/Scrum sprints.",
    stack: ["Next.js", "React Native", "NestJS", "GraphQL"],
    people: ["EVNS", "Arcarius Capital"],
  },
  {
    id: "nb-cicd",
    branch: "novabyte",
    date: "2025-07",
    approx: true,
    title: "Own CI/CD and infrastructure: GitHub Actions, AWS, MongoDB, Firebase",
    body: "Automated build-and-deploy pipelines running on every commit for every client platform.",
    stack: ["GitHub Actions", "AWS ECS", "S3", "MongoDB", "Firebase"],
  },
  {
    id: "nb-ai-layer",
    branch: "novabyte",
    date: "2025-10",
    approx: true,
    title: "Humanet AI layer on AWS Bedrock (Claude) in NestJS",
    body: "Conversational assistant, intent classification and structured clinical data extraction with source grounding, plus per-model token metering and monthly spend budgets.",
    stack: ["AWS Bedrock", "Claude", "NestJS", "TypeScript"],
    tags: ["production"],
  },
  {
    id: "nb-workflow",
    branch: "novabyte",
    date: "2026-02",
    approx: true,
    title: "Durable workflow-automation engine on BullMQ/Redis",
    body: "Event triggers, conditional branching, runtime variables and resumable steps driving appointments, clinical forms, prescriptions, referrals and tasks.",
    stack: ["BullMQ", "Redis", "NestJS"],
  },
  {
    id: "nb-scribe",
    branch: "novabyte",
    date: "2026-06",
    approx: true,
    title: "AI medical scribe: chunked audio → S3 → AWS Transcribe → SOAP note drafts",
    body: "Generated SOAP notes with evidence-linked suggested actions for clinicians to review.",
    stack: ["AWS Transcribe", "S3", "Bedrock", "NestJS"],
    tags: ["production"],
  },
];
