import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "humanet",
    name: "Humanet — AI layer for a healthcare EHR platform",
    owner: "NovaByte Solutions Inc.",
    period: "2025 – present",
    role: "Full-stack developer, owner of the AI and workflow layer",
    description:
      "Production electronic-health-record platform. Built the AI features clinicians use daily and the durable workflow engine behind appointments, forms, prescriptions, referrals and tasks.",
    highlights: [
      "Conversational assistant, intent classification and evidence-grounded clinical data extraction on AWS Bedrock (Claude) in NestJS.",
      "AI medical scribe: chunked audio upload to S3, AWS Transcribe processing, SOAP note drafts with evidence-linked suggested actions.",
      "Workflow-automation engine on BullMQ/Redis with event triggers, conditional branching, runtime variables and resumable steps.",
      "Per-model token metering and monthly spend budgeting so AI cost is visible and capped.",
    ],
    stack: ["NestJS", "TypeScript", "AWS Bedrock", "AWS Transcribe", "BullMQ", "Redis", "MongoDB", "S3"],
    branch: "novabyte",
    featured: true,
  },
  {
    id: "sabana-platform",
    name: "Sabana — ride-hailing platform",
    owner: "Sabana",
    period: "2018 – 2025",
    role: "Front-end → full-stack owner",
    description:
      "Driver app, customer product and partner admin panel, plus backend microservices. Grew from front-end feature work into ownership of the whole platform over seven years.",
    highlights: [
      "70% improvement in app performance across the driver and customer apps.",
      "Two production NestJS microservices: SMS notifications and an EU customs (ICS2/ENS) data-exchange integration, deployed via GitHub Actions.",
      "Shared, unit-tested UI component library giving web and mobile parity.",
      "Mentored junior developers through code review and pairing on React/React Native.",
    ],
    stack: ["React Native", "React", "Next.js", "TypeScript", "NestJS", "Node.js", "Jest", "GitHub Actions"],
    branch: "sabana",
    featured: true,
  },
  {
    id: "evns",
    name: "EVNS — Engel & Völkers Nova Scotia",
    owner: "NovaByte Solutions Inc.",
    period: "2025",
    role: "Full-stack developer across app, web and API",
    description:
      "Real-estate platform for Engel & Völkers Nova Scotia, live on the App Store, Google Play and the web. Involved in every layer: development, integration and deployment on all platforms.",
    highlights: [
      "React Native mobile app published on iOS and Android.",
      "Next.js website and Node.js/Express backend.",
    ],
    stack: ["React Native", "Next.js", "Node.js", "Express", "TypeScript"],
    links: [
      { label: "Website", href: "https://engelvoelkersnovascotia.com/" },
      { label: "App Store", href: "https://apps.apple.com/us/app/evns/id6746510960" },
      { label: "Google Play", href: "https://play.google.com/store/apps/details?id=com.novabyte.evnsappfrontend" },
    ],
    branch: "novabyte",
    featured: true,
  },
  {
    id: "hometrust",
    name: "HomeTrust",
    owner: "Client in Armenia",
    period: "Freelance",
    role: "Full-stack developer",
    description: "Built the admin panel in React and the main website in Next.js.",
    highlights: [],
    stack: ["React", "Next.js"],
    links: [{ label: "hometrust.sg", href: "https://hometrust.sg/" }],
    branch: "freelance",
  },
  {
    id: "dayra",
    name: "Dayra Club — mother application",
    owner: "Dr Maryam Abasi",
    period: "Freelance",
    role: "Full-stack developer",
    description: "Built the admin panel in Next.js and the web application in React with Vite.",
    highlights: [],
    stack: ["Next.js", "React", "Vite"],
    branch: "freelance",
  },
  {
    id: "hood-food",
    name: "Hood Food",
    owner: "Client in Armenia",
    period: "Freelance",
    role: "Mobile developer",
    description: "Two separate React Native apps, one for drivers and one for customers.",
    highlights: [],
    stack: ["React Native"],
    branch: "freelance",
  },
  {
    id: "rn-components",
    name: "React Native components on npm",
    owner: "Open source",
    period: "2022",
    role: "Author",
    description: "Two published components: a reusable button group and a searchable FlatList dropdown.",
    highlights: [],
    stack: ["React Native", "npm"],
    links: [
      { label: "react-native-gp-button", href: "https://www.npmjs.com/package/react-native-gp-button" },
      { label: "react-native-dropdown-searchable", href: "https://www.npmjs.com/package/react-native-dropdown-searchable" },
    ],
    branch: "oss",
  },
  {
    id: "vpn-tester",
    name: "windscribe-vpn-tester",
    owner: "Open source",
    period: "2026",
    role: "Author",
    description: "Tests every Windscribe location and protocol for latency and reliability on macOS and Windows.",
    highlights: [],
    stack: ["Node.js"],
    links: [{ label: "GitHub", href: "https://github.com/KianooshSoleimani/windscribe-vpn-tester" }],
    branch: "oss",
  },
];
